# Generated by Django 6.0.6 on 2026-07-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.mealingredients')),
            ],
        ),
    ]
