# Generated by Django 6.0.6 on 2026-06-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('meal_type', models.CharField(choices=[('BreakFast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prepare_time', models.IntegerField(help_text='Enter time in minute')),
            ],
            options={
                'db_table': 'meal',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mealplan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_plan',
            },
        ),
        migrations.CreateModel(
            name='MealPlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.mealplan')),
            ],
            options={
                'db_table': 'meal_plan_items',
            },
        ),
        migrations.CreateModel(
            name='MealIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
            options={
                'db_table': 'meal_ingredient',
                'unique_together': {('meal', 'ingredient')},
            },
        ),
    ]
