# Generated by Django 6.0.6 on 2026-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_payment_payment_method_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
